import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootProvider from "@/components/root-provider/root-provider";
import "@ant-design/v5-patch-for-react-19";

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 👇 keep RootLayout a SERVER component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Move AntD patch into RootProvider so this stays server-safe */}
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
